[package]
name = "chess_dl"
version = "0.3.4"
authors = ["Nimrod Hajaj <rodhajaj@gmail.com>"]
edition = "2018"
repository = "https://github.com/nimr0d/chess_dl"
description = "Chess.com game downloader"
license = "MIT"
readme = "README.md"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11.11", features = ["blocking", "json"] }
serde = { version = "1.0.137", features = ["derive"] }
tempfile = "3.3.0"
futures = "0.3.21"
tokio = { version = "1.19.2", features = ["full"] }
crossbeam-channel = "0.5.5"
bytes = "1.1.0"
log = "0.4.17"
env_logger = "0.9.0"
pest = "2.1.3"
pest_derive = "2.1.0"
peg = "0.8.0"
clap = { version = "3.2.6", features = ["derive"] }
strum = { version = "0.24.1", features = ["derive"] }
itertools = "0.10.3"
