[package]
name = "chess_dl"
version = "0.3.9"
authors = ["Nimrod Hajaj <ndh42@cornell.edu>"]
edition = "2018"
repository = "https://github.com/nimr0d/chess_dl"
description = "Chess.com game downloader"
license = "MIT"
readme = "README.md"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11.14", features = ["blocking", "json"] }
serde = { version = "1.0.152", features = ["derive"] }
tempfile = "3.3.0"
futures = "0.3.26"
tokio = { version = "1.25.0", features = ["full"] }
crossbeam-channel = "0.5.6"
bytes = "1.4.0"
log = "0.4.17"
env_logger = "0.10.0"
pest = "2.5.5"
pest_derive = "2.5.5"
peg = "0.8.1"
clap = { version = "4.1.6", features = ["derive"] }
strum = { version = "0.24.1", features = ["derive"] }
itertools = "0.10.5"
